// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lPVubJgmm8-KBsnTtZMGh9E61YurUBU',
    appId: '1:632418318888:web:0fee06b6b7b7169152131d',
    messagingSenderId: '632418318888',
    projectId: 'eventwise-cb24f',
    authDomain: 'eventwise-cb24f.firebaseapp.com',
    databaseURL: 'https://eventwise-cb24f-default-rtdb.firebaseio.com',
    storageBucket: 'eventwise-cb24f.firebasestorage.app',
    measurementId: 'G-4H3FDZBPYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPhGTDRl5JdZiyzi0rJG8ZEC87IZu-W8',
    appId: '1:632418318888:android:6dc481155b9fd5ab52131d',
    messagingSenderId: '632418318888',
    projectId: 'eventwise-cb24f',
    databaseURL: 'https://eventwise-cb24f-default-rtdb.firebaseio.com',
    storageBucket: 'eventwise-cb24f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZtlICoewi4164TgqrmY_TsZ9_1GLKM-o',
    appId: '1:632418318888:ios:2905b553e960a18a52131d',
    messagingSenderId: '632418318888',
    projectId: 'eventwise-cb24f',
    databaseURL: 'https://eventwise-cb24f-default-rtdb.firebaseio.com',
    storageBucket: 'eventwise-cb24f.firebasestorage.app',
    iosBundleId: 'com.example.eventWise2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZtlICoewi4164TgqrmY_TsZ9_1GLKM-o',
    appId: '1:632418318888:ios:2905b553e960a18a52131d',
    messagingSenderId: '632418318888',
    projectId: 'eventwise-cb24f',
    databaseURL: 'https://eventwise-cb24f-default-rtdb.firebaseio.com',
    storageBucket: 'eventwise-cb24f.firebasestorage.app',
    iosBundleId: 'com.example.eventWise2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8lPVubJgmm8-KBsnTtZMGh9E61YurUBU',
    appId: '1:632418318888:web:9b945176fd50b28552131d',
    messagingSenderId: '632418318888',
    projectId: 'eventwise-cb24f',
    authDomain: 'eventwise-cb24f.firebaseapp.com',
    databaseURL: 'https://eventwise-cb24f-default-rtdb.firebaseio.com',
    storageBucket: 'eventwise-cb24f.firebasestorage.app',
    measurementId: 'G-YF4KRVSHDQ',
  );

}